name: 部署網站

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'  # 每6小時更新

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      
    - name: 設定 R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        
    - name: 快取 R 套件
      uses: actions/cache@v4
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-
        
    - name: 安裝 R 套件
      run: |
        # 只安裝缺少的套件
        needed <- c("tidyverse", "plotly", "DT", "gh")
        installed <- rownames(installed.packages())
        to_install <- setdiff(needed, installed)
        
        if (length(to_install) > 0) {
          install.packages(to_install)
        } else {
          cat("所有套件已安裝\n")
        }
      shell: Rscript {0}
      
    - name: 更新資料
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 從各 repo 收集最新預測
        Rscript scripts/collect_forecasts.R
        
    - name: 建置網站
      run: |
        quarto render
        
    - name: 部署到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site